@LF10.Api_HostAddress = http://localhost:5273

GET {{LF10.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{LF10.Api_HostAddress}}/api/harassmentfilter
Content-Type: application/json

"i hate you!"

###